version: '3.8'

services:
  # frontend isnt quite ready yet dont build it 
  # frontend:
  #   build: ../frontend
  #   container_name: frontend
  #   environment:
  #     - Backend_URL=http://backend:2500 #this is only the backend url when the frontend is containerized inside docker compose!
  #     - KEYCLOAK_URL=http://keycloak:8080 #this is only the keycloak url when the frontend is containerized inside docker compose!
  #   ports:
  #     - "80:3000"
  #   depends_on:
  #     - mysql
  #     - backend
  #   entrypoint: npm run start.
  # backend:
  #   build: ../kcbackend
  #   container_name: backend
  #   environment:
  #     - KEYCLOAK_REALM=biovault
  #     - KEYCLOAK_CLIENT=backend
  #     - KEYCLOAK_CLIENT_SECRET=Qi96ntCsIBvnX4RFydt3zCmTeJZ7jbSR
  #     # - TOKEN_URL=http://keycloak:8080/realms/biovault/protocol/openid-connect/token
  #     - KEYCLOAK_URL=http://keycloak:8080 #this is only the keycloak url when the backend is containerized inside docker compose!
  #     - DB_PORT=3306
  #     - DB_USER=root
  #     - DB=biometric_auth
  #     - DB_HOST=mysql
  #     - DB_PASS=secretsquirrels
  #   restart: always
  #   ports:
  #     - "2500:2500"
  #   expose:
  #     - 2500
  #   depends_on:
  #     - mysql
  #     - keycloak
  #   entrypoint: node server.js
  keycloak:
    build: ./../keycloak
    container_name: keycloak
    depends_on:
      - mysql
    expose:
      - 8080
    ports:
      - "8080:8080"
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://mysql:3306/biometric_auth
      - KC_DB_USERNAME=root
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_HTTPS_PORT=8443
    entrypoint: ["/opt/keycloak/bin/kc.sh","start-dev" ]
  mysql:
    # image: mysql:latest
    build: ../mysql/.
    container_name: BioVault
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: secretsquirrels
      MYSQL_DATABASE: biometric_auth
      MYSQL_USER: mashedsnake
      MYSQL_PASSWORD: ilovelamp
    command:  --character-set-server=utf8 
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data: