version: '3.8'

services:
  web:
    build: .
    container_name: web_app
    ports:
      - "8000:5000"  
    volumes:
      - .:/app  
    depends_on:
      - mysql  
    environment:
      - FLASK_ENV=development

  mysql:
    image: mysql:latest
    container_name: BioVault
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretsquirrels
      MYSQL_DATABASE: biometric_auth
      MYSQL_USER: mashedsnake
      MYSQL_PASSWORD: ilovelamp
    command:  --character-set-server=utf8 
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql  
  keycloak:
    container_name: keycloak
    ports:
      - "80:8080"
    image: quay.io/keycloak/keycloak:26.0.0
    environment:
      - KC_DB=mysql
      - KC_DB_PASSWORD=secretsquirrels
      - KC_DB_URL=jdbc:mysql://mysql:3306/biometric_auth
      - KC_DB_USERNAME=root
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
    entrypoint: ["/opt/keycloak/bin/kc.sh","start-dev" ]
  
volumes:
  mysql_data: