CREATE TABLE IF NOT EXISTS biometric_auth.USER_ENTITY (
 ID INT AUTO_INCREMENT PRIMARY KEY,
 EMAIL VARCHAR(55) NOT NULL,
 USERNAME VARCHAR(30) NOT NULL,
 pass_word VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS biometric_auth.wpm (
 wpm_id PRIMARY KEY AUTO_INCREMENT,
n

 value REAL
 FOREIGN KEY (ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS biometric_auth.keys_per_sec (
 keys_per_sec_id PRIMARY KEY AUTO_INCREMENT,
 value REAL,
 
 FOREIGN KEY (ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS biometric_auth.avg_dwell_time (
 avg_dwell_time_id PRIMARY KEY AUTO_INCREMENT,
 value REAL,
 FOREIGN KEY (ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS biometric_auth.avg_time_between_keystrokes (
 avg_time_between_keystrokes_id PRIMARY KEY AUTO_INCREMENT,
 value REAL,
 FOREIGN KEY (ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS biometric_auth.avg_click_dwell_time (
 avg_click_dwell_time_wpm_id PRIMARY KEY AUTO_INCREMENT,
 value REAL,
 FOREIGN KEY (ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS biometric_auth.mouse_speed (
 mouse_speed_id PRIMARY KEY AUTO_INCREMENT,
 value REAL,
 FOREIGN KEY (ID) REFERENCES USER_ENTITY(ID)
);