-- CREATE TABLE IF NOT EXISTS USER_ENTITY (
--     ID INT AUTO_INCREMENT PRIMARY KEY,
--     EMAIL VARCHAR(55) NOT NULL,
--     USERNAME VARCHAR(30) NOT NULL,
--     pass_word VARCHAR(255) NOT NULL
-- );

-- CREATE TABLE IF NOT EXISTS wpm (
--     wpm_id INT PRIMARY KEY AUTO_INCREMENT,
--     value REAL,
--     USER_ID INT,
--     FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY(ID)
-- );

CREATE TABLE IF NOT EXISTS keys_per_sec (
    keys_per_sec_id INT PRIMARY KEY AUTO_INCREMENT,
    value REAL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS avg_dwell_time (
    avg_dwell_time_id INT PRIMARY KEY AUTO_INCREMENT,
    value REAL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS avg_time_between_keystrokes (
    avg_time_between_keystrokes_id INT PRIMARY KEY AUTO_INCREMENT,
    value REAL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS avg_click_dwell_time (
    avg_click_dwell_time_id INT PRIMARY KEY AUTO_INCREMENT,
    value REAL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS mouse_speed (
    mouse_speed_id INT PRIMARY KEY AUTO_INCREMENT,
    value REAL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER_ENTITY(ID)
);
